"""empty message

Revision ID: 1bf46ac6f8d3
Revises: cd4fb0913be6
Create Date: 2019-11-26 10:55:20.083231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bf46ac6f8d3'
down_revision = 'cd4fb0913be6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instrument',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('heading', sa.String(), nullable=True),
    sa.Column('body', sa.String(), nullable=True),
    sa.Column('preview_text', sa.String(), nullable=True),
    sa.Column('footnote', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('instrument', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_instrument_timestamp'), ['timestamp'], unique=False)

    op.create_table('thesis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('heading', sa.String(), nullable=True),
    sa.Column('body', sa.String(), nullable=True),
    sa.Column('preview_text', sa.String(), nullable=True),
    sa.Column('footnote', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('thesis', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_thesis_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('thesis', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_thesis_timestamp'))

    op.drop_table('thesis')
    with op.batch_alter_table('instrument', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_instrument_timestamp'))

    op.drop_table('instrument')
    # ### end Alembic commands ###
