"""empty message

Revision ID: 23949695db32
Revises: 88301f6be966
Create Date: 2019-11-26 00:32:53.874735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23949695db32'
down_revision = '88301f6be966'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('human_group')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('human_group',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=True),
    sa.Column('human_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['human_id'], ['human.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###
