"""empty message

Revision ID: 2758422fcd63
Revises: ac960d381b3b
Create Date: 2019-11-08 10:26:54.609403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2758422fcd63'
down_revision = 'ac960d381b3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('human', 'ids')
    op.drop_column('human', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('human', sa.Column('name', sa.VARCHAR(length=64), nullable=True))
    op.add_column('human', sa.Column('ids', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
