"""empty message

Revision ID: 2e955dda2d0e
Revises: 1bf46ac6f8d3
Create Date: 2019-11-26 11:20:44.680838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e955dda2d0e'
down_revision = '1bf46ac6f8d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instrument', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_heading', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instrument', schema=None) as batch_op:
        batch_op.drop_column('full_heading')

    # ### end Alembic commands ###
