"""added article heading

Revision ID: 892031a4f908
Revises: e9878a19442e
Create Date: 2019-08-26 16:33:15.403210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '892031a4f908'
down_revision = 'e9878a19442e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('heading', sa.String(), nullable=True))
    op.create_index(op.f('ix_human_email'), 'human', ['email'], unique=True)
    op.create_index(op.f('ix_human_full_name'), 'human', ['full_name'], unique=True)
    op.create_index(op.f('ix_human_name'), 'human', ['name'], unique=True)
    op.drop_column('human', 'ids')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('human', sa.Column('ids', sa.VARCHAR(), nullable=True))
    op.drop_index(op.f('ix_human_name'), table_name='human')
    op.drop_index(op.f('ix_human_full_name'), table_name='human')
    op.drop_index(op.f('ix_human_email'), table_name='human')
    op.drop_column('article', 'heading')
    # ### end Alembic commands ###
