"""empty message

Revision ID: 91283325ed41
Revises: 2758422fcd63
Create Date: 2019-11-08 10:30:11.292370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91283325ed41'
down_revision = '2758422fcd63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('human', 'ids')
    op.drop_column('human', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('human', sa.Column('name', sa.VARCHAR(length=64), nullable=True))
    op.add_column('human', sa.Column('ids', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
