"""empty message

Revision ID: 9e337f04f46a
Revises: c94cdae2830b
Create Date: 2019-11-08 10:38:16.367835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e337f04f46a'
down_revision = 'c94cdae2830b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('human') as batch_op:
        batch_op.drop_column('ids')
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('human', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=64), nullable=True))
        batch_op.add_column(sa.Column('ids', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
