"""add new people column - group

Revision ID: ab356eb51c25
Revises: 9e337f04f46a
Create Date: 2019-11-08 13:24:12.414934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab356eb51c25'
down_revision = '9e337f04f46a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('human', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_human_group'), ['group'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('human', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_human_group'))
        batch_op.drop_column('group')

    # ### end Alembic commands ###
