"""empty message

Revision ID: b92b045c06de
Revises: ab356eb51c25
Create Date: 2019-11-25 23:51:18.860108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b92b045c06de'
down_revision = 'ab356eb51c25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('human_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('human_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['human_id'], ['human.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('human', schema=None) as batch_op:
        batch_op.drop_index('ix_human_group')
        batch_op.drop_column('group')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('human', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group', sa.VARCHAR(), nullable=True))
        batch_op.create_index('ix_human_group', ['group'], unique=False)

    op.drop_table('human_group')
    # ### end Alembic commands ###
