"""empty message

Revision ID: c94cdae2830b
Revises: 39881a309f40
Create Date: 2019-11-08 10:33:50.179483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c94cdae2830b'
down_revision = '39881a309f40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('human', 'name')
    op.drop_column('human', 'ids')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('human', sa.Column('ids', sa.VARCHAR(), nullable=True))
    op.add_column('human', sa.Column('name', sa.VARCHAR(length=64), nullable=True))
    # ### end Alembic commands ###
