"""empty message

Revision ID: cd4fb0913be6
Revises: 23949695db32
Create Date: 2019-11-26 09:07:30.972514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd4fb0913be6'
down_revision = '23949695db32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('heading', sa.String(), nullable=True),
    sa.Column('body', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('grant', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_grant_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grant', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_grant_timestamp'))

    op.drop_table('grant')
    # ### end Alembic commands ###
