"""

Revision ID: d75a1ca1e39e
Revises: f100a974b9be
Create Date: 2019-10-27 12:38:17.955295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd75a1ca1e39e'
down_revision = 'f100a974b9be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('human', sa.Column('about_text', sa.String(length=64), nullable=True))
    op.add_column('human', sa.Column('full_name_cz', sa.String(length=64), nullable=True))
    op.add_column('human', sa.Column('slug', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_human_email'), 'human', ['email'], unique=True)
    op.create_index(op.f('ix_human_full_name'), 'human', ['full_name'], unique=True)
    op.create_index(op.f('ix_human_full_name_cz'), 'human', ['full_name_cz'], unique=True)
    op.create_index(op.f('ix_human_slug'), 'human', ['slug'], unique=True)
    op.drop_column('human', 'name')
    op.drop_column('human', 'ids')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('human', sa.Column('ids', sa.VARCHAR(), nullable=True))
    op.add_column('human', sa.Column('name', sa.VARCHAR(length=64), nullable=True))
    op.drop_index(op.f('ix_human_slug'), table_name='human')
    op.drop_index(op.f('ix_human_full_name_cz'), table_name='human')
    op.drop_index(op.f('ix_human_full_name'), table_name='human')
    op.drop_index(op.f('ix_human_email'), table_name='human')
    op.drop_column('human', 'slug')
    op.drop_column('human', 'full_name_cz')
    op.drop_column('human', 'about_text')
    # ### end Alembic commands ###
