"""new fields for Article and new Human Models

Revision ID: daa79025f24b
Revises: 6ff7ee0bcaee
Create Date: 2019-07-08 13:29:31.555718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'daa79025f24b'
down_revision = '6ff7ee0bcaee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('article_type', sa.String(length=64), nullable=True))
    op.add_column('human', sa.Column('email', sa.String(length=120), nullable=True))
    op.add_column('human', sa.Column('full_name', sa.String(length=64), nullable=True))
    op.add_column('human', sa.Column('ids', sa.String(), nullable=True))
    op.add_column('human', sa.Column('links', sa.String(length=120), nullable=True))
    op.add_column('human', sa.Column('name', sa.String(length=64), nullable=True))
    op.add_column('human', sa.Column('position', sa.String(length=64), nullable=True))
    op.add_column('human', sa.Column('telephone', sa.String(length=120), nullable=True))
    op.create_index(op.f('ix_human_email'), 'human', ['email'], unique=True)
    op.create_index(op.f('ix_human_full_name'), 'human', ['full_name'], unique=True)
    op.create_index(op.f('ix_human_name'), 'human', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_human_name'), table_name='human')
    op.drop_index(op.f('ix_human_full_name'), table_name='human')
    op.drop_index(op.f('ix_human_email'), table_name='human')
    op.drop_column('human', 'telephone')
    op.drop_column('human', 'position')
    op.drop_column('human', 'name')
    op.drop_column('human', 'links')
    op.drop_column('human', 'ids')
    op.drop_column('human', 'full_name')
    op.drop_column('human', 'email')
    op.drop_column('article', 'article_type')
    # ### end Alembic commands ###
