"""empty message

Revision ID: df455d84e06a
Revises: b92b045c06de
Create Date: 2019-11-25 23:59:23.552171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df455d84e06a'
down_revision = 'b92b045c06de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('human', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group', sa.String(), nullable=True))
        batch_op.create_foreign_key(None, 'human_group', ['group'], ['id'])

    with op.batch_alter_table('human_group', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('human_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('human_group', schema=None) as batch_op:
        batch_op.add_column(sa.Column('human_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'human', ['human_id'], ['id'])

    with op.batch_alter_table('human', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('group')

    # ### end Alembic commands ###
