"""empty message

Revision ID: f4624660406b
Revises: df455d84e06a
Create Date: 2019-11-26 00:14:37.160306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4624660406b'
down_revision = 'df455d84e06a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('human', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group', sa.String(), nullable=True))
        batch_op.create_foreign_key(None, 'human_group', ['group'], ['id'])

    with op.batch_alter_table('human_group', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('human_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('human_group', schema=None) as batch_op:
        batch_op.add_column(sa.Column('human_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'human', ['human_id'], ['id'])

    with op.batch_alter_table('human', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('group')

    # ### end Alembic commands ###
